# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.

colorScheme = "blowfish"
defaultAppearance = "light" # valid options: light or dark
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true

mainSections = ["posts", "suggest", "external"]
# robots = ""

[header]
  layout = "fixed"

[footer]
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "background" # valid options: page, profile, custom
  homepageImage = "img/background.png"
  showRecent = true
  showRecentItems = 10
  showMoreLink = true
  showMoreLinkDest = '/posts'
  cardView = false
  cardViewScreenWidth = false
  layoutBackgroundBlur = true

[article]
  showDate = true
  showViews = true
  showLikes = false
  showDateUpdated = false
  showAuthor = false
  heroStyle = "background"
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  editURL = "https://github.com/nunocoracao/homepage/tree/main/content"
  editAppendPath = true
  seriesOpened = true
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = true 
  showAuthorsBadges = true
  showWordCount = false
  showSummary = true
  sharingLinks = [ "linkedin", "twitter", "whatsapp", "pinterest", "reddit", "facebook", "email"]

[list]
  showHero = true
  heroStyle = "background"
  showBreadcrumbs = false
  showViews = true
  showLikes = false
  showSummary = false
  showTableOfContents = false
  showCards = true
  groupByYear = true
  cardView = false
  cardViewScreenWidth = false

[sitemap]
  excludedKinds = ["taxonomy", "term"]

[taxonomy]
  showTermCount = true

[firebase]
  apiKey = "AIzaSyAN9vJzbGcqXi3fCiakI8rCVV7-S6T8n4s"
  authDomain = "homepage-a0c38.firebaseapp.com"
  projectId = "homepage-a0c38"
  storageBucket = "homepage-a0c38.appspot.com"
  messagingSenderId = "722874298820"
  appId = "1:722874298820:web:b5c0e707586eba68c43491"
  measurementId = "G-H8CSEYZFG4"

[fathomAnalytics]
  # site = "ABC12345"
  # domain = "llama.yoursite.com"

[verification]
  # google = ""
  # bing = ""
  # pinterest = ""
  # yandex = ""
